version: '3.8'

services:
  db:
    image: postgres:15
    container_name: portos_db
    environment:
      POSTGRES_DB: portos-estagio
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: dbaaccesskey
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: portos_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:dbaaccesskey@db:5432/portos-estagio
    volumes:
      - ./backend:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portos_frontend
    ports:
      - "3000:80"


  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: portos_etl
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:dbaaccesskey@db:5432/portos-estagio
    volumes:
      - ./etl:/app
      - ./db:/db


volumes:
  postgres_data:
